family = "Fruit Salad"
output_file = "fruit-salad.ttf"
color_format = "glyf_colr_1"

clipbox_quantization = 32

[axis.wght]
name = "Weight"
default = 400

[master.regular]
style_name = "Regular"

srcs = [
    "src/u002a.svg",
    "src/u002b.svg",
    "src/u002c.svg",
    "src/u002d.svg",
    "src/u002e.svg",
    "src/u003a.svg",
    "src/u003b.svg",
    "src/u003c.svg",
    "src/u003d.svg",
    "src/u003e.svg",
    "src/u003f.svg",
    "src/u004a.svg",
    "src/u004b.svg",
    "src/u004c.svg",
    "src/u004d.svg",
    "src/u004e.svg",
    "src/u004f.svg",
    "src/u005a.svg",
    "src/u005e.svg",
    "src/u005f.svg",
    "src/u006a.svg",
    "src/u006b.svg",
    "src/u006c.svg",
    "src/u006d.svg",
    "src/u006e.svg",
    "src/u006f.svg",
    "src/u007a.svg",
    "src/u0021.svg",
    "src/u0022.svg",
    "src/u0023.svg",
    "src/u0024.svg",
    "src/u0026.svg",
    "src/u0027.svg",
    "src/u0028.svg",
    "src/u0029.svg",
    "src/u0030.svg",
    "src/u0031.svg",
    "src/u0032.svg",
    "src/u0033.svg",
    "src/u0034.svg",
    "src/u0035.svg",
    "src/u0036.svg",
    "src/u0037.svg",
    "src/u0038.svg",
    "src/u0039.svg",
    "src/u0040.svg",
    "src/u0041.svg",
    "src/u0042.svg",
    "src/u0043.svg",
    "src/u0044.svg",
    "src/u0045.svg",
    "src/u0046.svg",
    "src/u0047.svg",
    "src/u0048.svg",
    "src/u0049.svg",
    "src/u0050.svg",
    "src/u0051.svg",
    "src/u0052.svg",
    "src/u0053.svg",
    "src/u0054.svg",
    "src/u0055.svg",
    "src/u0056.svg",
    "src/u0057.svg",
    "src/u0058.svg",
    "src/u0059.svg",
    "src/u0061.svg",
    "src/u0062.svg",
    "src/u0063.svg",
    "src/u0064.svg",
    "src/u0065.svg",
    "src/u0066.svg",
    "src/u0067.svg",
    "src/u0068.svg",
    "src/u0069.svg",
    "src/u0070.svg",
    "src/u0071.svg",
    "src/u0072.svg",
    "src/u0073.svg",
    "src/u0074.svg",
    "src/u0075.svg",
    "src/u0076.svg",
    "src/u0077.svg",
    "src/u0078.svg",
    "src/u0079.svg",
]

[master.regular.position]
wght = 400